[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build]
  command = "ng build --configuration production"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-inline-functions-env"

[[headers]]
  for = "/assets/config.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
